name: Cucumber Tests Scheduler

on:
  schedule:
    - cron: '0/5 * * * *'

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Cucumber Tests on ${{ matrix.browser }}
        run: mvn clean verify -Dbrowser=${{ matrix.browser }}

      - name: Upload Cucumber Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report-${{ matrix.browser }}
          path: target/cucumber-html-reports

      - name: Upload Generated Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generated-artifacts-${{ matrix.browser }}
          path: target
