name: Cucumber Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - edge

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cek versi browser dan WebDriver
        run: |
              $commands = @{
              "Google Chrome" = "C:\Program Files\Google\Chrome\Application\chrome.exe --version"
              "ChromeDriver"  = "C:\SeleniumWebDrivers\ChromeDriver\chromedriver.exe --version"
              "Mozilla Firefox" = "C:\Program Files\Mozilla Firefox\firefox.exe --version"
              "GeckoDriver"   = "C:\SeleniumWebDrivers\GeckoDriver\geckodriver.exe --version"
              "Microsoft Edge" = "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --version"
              "Edge WebDriver" = "C:\SeleniumWebDrivers\EdgeDriver\msedgedriver.exe --version"
              }

              foreach ($name in $commands.Keys) {
               Write-Output "$name:"
               $command = $commands[$name]
               if (Test-Path $command.Split(" ")[0]) {
                & $command
               } else {
                Write-Output "$name tidak ditemukan"
               }
              }
        shell: pwsh

      
      - name: Run Cucumber Tests ${{ github.event.inputs.browser }}
        run: mvn clean verify -Dbrowser=${{ github.event.inputs.browser }}

      - name: Upload Cucumber Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-html-reports

      - name: Upload Generated Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generated-artifacts
          path: target
