name: Cucumber Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - edge

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cek Versi Browser & WebDriver (Windows)
        run: |
              echo "Chrome:"
              (Get-ItemProperty "HKLM:\Software\Google\Chrome\BLBeacon").Version
              echo "Firefox:"
              (Get-Command "C:\Program Files\Mozilla Firefox\firefox.exe").Version
              echo "Edge:"
              (Get-ItemProperty "HKLM:\Software\Microsoft\Edge\BLBeacon").Version

              echo "Chromedriver:"
              (Get-Command chromedriver).Source
              chromedriver --version

              echo "Geckodriver:"
              (Get-Command geckodriver).Source
              geckodriver --version

              echo "MSEdgeDriver:"
              (Get-Command msedgedriver).Source
              msedgedriver --version
        shell: pwsh



      - name: Run Cucumber Tests ${{ github.event.inputs.browser }}
        run: mvn clean verify -Dbrowser=${{ github.event.inputs.browser }}

      - name: Upload Cucumber Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-html-reports

      - name: Upload Generated Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generated-artifacts
          path: target
