name: Cucumber Tests (All OS)

on:
  schedule:
    - cron: "0 0 * * *"  # Jalan otomatis setiap hari
  workflow_dispatch:  # Bisa dijalankan manual tanpa input
  push:
    branches:
      - windows
      - ubuntu
      - macos

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            branch: windows
            browsers: [chrome, firefox, edge]

          - os: ubuntu-latest
            branch: ubuntu
            browsers: [chrome, firefox, edge]

          - os: macos-latest
            branch: macos
            browsers: [chrome, safari]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Check Browser Versions (Ubuntu & macOS)
        if: matrix.os != 'windows-latest'
        run: |
          echo "Chrome:" && google-chrome --version || true
          echo "Firefox:" && firefox --version || true
          echo "Edge:" && microsoft-edge --version || true
          which chromedriver && chromedriver --version || true
          which geckodriver && geckodriver --version || true
          which msedgedriver && msedgedriver --version || true
          which safaridriver && safaridriver --version || true

      - name: Enable Safari Remote Automation
        if: matrix.os == 'macos-latest'
        run: |
          sudo safaridriver --enable
          defaults write com.apple.Safari AllowRemoteAutomation -bool true
          sudo killall safaridriver || true

      - name: Run Cucumber Tests for ${{ matrix.os }}
        run: |
          for browser in ${{ join(matrix.browsers, ' ') }}; do
            echo "Running tests on $browser..."
            mvn clean verify -Dbrowser=$browser
          done

      - name: Upload Cucumber Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report-${{ matrix.os }}
          path: target/cucumber-html-reports
