name: Cucumber Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Browser'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - edge

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Log Start Time (WIB)
        run: echo "Job started at $(TZ=Asia/Jakarta date)"

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Check Browser versions
        run: |
              echo "Chrome:"
              google-chrome --version
              echo "Firefox:"
              firefox --version
              echo "Edge:"
              microsoft-edge --version
              which chromedriver
              chromedriver --version
              which geckodriver
              geckodriver --version
              which msedgedriver
              msedgedriver --version

      - name: Run Cucumber Tests ${{ github.event.inputs.browser }}
        run: mvn clean verify -Dbrowser=${{ github.event.inputs.browser }}

      - name: Upload Cucumber Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-html-reports

      - name: Upload Generated Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generated-artifacts
          path: target
