name: List Directories (Ubuntu)

on: [workflow_dispatch]  # Bisa dijalankan manual

jobs:
  list-root-directories:
    runs-on: ubuntu-latest

    steps:
      - name: Print Current User and Home
        run: |
          whoami
          echo "Home Directory: $HOME"

      - name: List Root Directories
        run: ls -lah /

      - name: List All Files in /usr/bin
        run: ls -lah /usr/bin

      - name: Count Total Files in /usr/bin
        run: ls /usr/bin | wc -l

      - name: Find Specific Binaries
        run: |
          which java || echo "Java not found"
          which python || echo "Python not found"
          which mvn || echo "Maven not found"

      - name: Show First 20 Files in /usr/bin
        run: ls /usr/bin | head -n 20
