name: List Directories (Ubuntu)

on: [workflow_dispatch]  # Bisa dijalankan manual

jobs:
  list-directories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Current Directory
        run: pwd

      - name: List All Files and Directories
        run: ls -lah

      - name: List Only Directories
        run: ls -d */

      - name: Find All Directories Recursively
        run: find . -type d

      - name: Install and Show Directory Tree
        run: |
          sudo apt-get update
          sudo apt-get install -y tree
          tree -L 2
