name: List Directories in GitHub Actions (Windows)

on:
  workflow_dispatch:

jobs:
  list-directories:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List all directories (PowerShell)
        run: Get-ChildItem -Path . -Recurse
        shell: pwsh

      - name: Show workspace directory
        run: Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse
        shell: pwsh

      - name: Show home directory
        run: Get-ChildItem -Path $env:USERPROFILE -Recurse
        shell: pwsh

      - name: List all files and folders in C:\
        run: Get-ChildItem -Path C:\ -Force
        shell: pwsh

      - name: Explore Directories Step by Step
        run: |
            echo "Listing Root Directory:"
            dir C:\
            echo "Listing Program Files:"
            dir 'C:\Program Files'
            echo "Listing Android:"
            dir 'C:\Android'
            echo "Listing SeleniumWebDrivers:"
            dir 'C:\SeleniumWebDrivers'
            dir 'C:\SeleniumWebDrivers\ChromeDriver'
            dir 'C:\SeleniumWebDrivers\EdgeDriver'
            dir 'C:\SeleniumWebDrivers\GeckoDriver'
            dir 'C:\SeleniumWebDrivers\IEDriver'
        shell: pwsh

