name: Cucumber Tests Scheduler Ubuntu

on:
  schedule:
    - cron: '0 17,1,9 * * *'
  push:
    branches:
      - ubuntu

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - name: Log Start Time (WIB) on Ubuntu
        run: |
            export TZ=Asia/Jakarta
            FORMATTED_TIME=$(date +"%A, %-d %B %Y - %H:%M:%S WIB")
            echo "Job started at $FORMATTED_TIME"

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ubuntu 

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Check Browser versions
        run: |
              echo "Chrome:"
              google-chrome --version
              echo "Firefox:"
              firefox --version
              echo "Edge:"
              microsoft-edge --version
              which chromedriver
              chromedriver --version
              which geckodriver
              geckodriver --version
              which msedgedriver
              msedgedriver --version

      - name: Run Cucumber Tests on ${{ matrix.browser }}
        run: mvn clean verify -Dbrowser=${{ matrix.browser }}

      - name: Upload Cucumber Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report-${{ matrix.browser }}
          path: target/cucumber-html-reports

      - name: Upload Generated Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generated-artifacts-${{ matrix.browser }}
          path: target
